In [1]:
import numpy as np

X= np.array([
    [10, 20, 30], [40, 50, 60], [70, 80, 90]
])

# second row
print(X[1])  

#1st row 3rd column
print(X[1,2])

#all rows first column 
print(X[:, 0])

#reshape without changing no. of elements
v= np.arange(6)
N= v.reshape(2, 3)

print(N)

[40 50 60]
60
[10 40 70]
[[0 1 2]
 [3 4 5]]


In [2]:
import torch

# create 2D tensor
X= torch.tensor([
    [1.0, 2.0], [3.0, 4.0], [5.0, 6.0]
])

print(X.shape)
print(X.ndim)
print(X.dtype)

# Create a batch of 32 RGB images of size 224 x 224
images= torch.randn(32, 3, 224, 224)

print(images.shape)

torch.Size([3, 2])
2
torch.float32
torch.Size([32, 3, 224, 224])
